import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { useRoastStore } from '../store/roast';
import { RoastCard } from './RoastCard';
import { MetricsGrid } from './MetricsGrid';
import { FinalVerdict } from './FinalVerdict';
export function RoastReveal() {
    const { analysis, revealed, revealNextRoast, revealAll, showVerdict, setShowVerdict } = useRoastStore();
    if (!analysis)
        return null;
    const allRevealed = revealed >= analysis.roasts.length;
    return (_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "min-h-screen bg-gradient-to-b from-dark-950 via-dark-900 to-dark-950", children: _jsxs("div", { className: "max-w-3xl mx-auto px-4 py-12", children: [_jsxs(motion.div, { initial: { opacity: 0, y: -20 }, animate: { opacity: 1, y: 0 }, className: "text-center mb-12", children: [_jsxs("h2", { className: "text-4xl font-bold mb-2", children: ["@", analysis.username] }), _jsx(motion.div, { initial: { scale: 0.5, opacity: 0 }, animate: { scale: 1, opacity: 1 }, transition: { delay: 0.3 }, className: "inline-block", children: _jsx("div", { className: "w-32 h-32 rounded-full bg-gradient-to-br from-neon-purple to-neon-cyan\r\n                         flex items-center justify-center mb-6", children: _jsx("span", { className: "text-5xl font-bold text-dark-900", children: analysis.overall_score }) }) }), _jsxs("p", { className: "text-gray-400 text-lg", children: ["Roast Score: ", analysis.overall_score > 70 ? '🔥 Critical' : analysis.overall_score > 40 ? '⚠️ Severe' : '✓ Okay'] })] }), _jsx(MetricsGrid, { metrics: analysis.metrics }), _jsxs("div", { className: "mt-16 mb-12", children: [_jsx("h3", { className: "text-2xl font-bold text-neon-cyan mb-8", children: "The Roasts" }), _jsx("div", { className: "space-y-4", children: analysis.roasts.map((roast, index) => (_jsx(RoastCard, { roast: roast, index: index, isRevealed: index < revealed }, index))) })] }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.5 }, className: "flex gap-4 justify-center mb-8", children: !allRevealed ? (_jsxs(_Fragment, { children: [_jsx(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, onClick: revealNextRoast, className: "px-6 py-2 bg-neon-purple text-dark-900 font-bold rounded-lg\r\n                         hover:shadow-lg hover:shadow-neon-purple/50 transition-all", children: "Next Roast" }), _jsx(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, onClick: revealAll, className: "px-6 py-2 bg-neon-cyan text-dark-900 font-bold rounded-lg\r\n                         hover:shadow-lg hover:shadow-neon-cyan/50 transition-all", children: "Show All" })] })) : (_jsx(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, onClick: () => setShowVerdict(!showVerdict), className: "px-6 py-2 bg-gradient-to-r from-neon-green to-neon-cyan text-dark-900\r\n                       font-bold rounded-lg hover:shadow-lg transition-all", children: showVerdict ? 'Hide Verdict' : 'Final Verdict' })) }), _jsx(AnimatePresence, { children: showVerdict && _jsx(FinalVerdict, { verdict: analysis.final_verdict }) })] }) }));
}
//# sourceMappingURL=RoastReveal.js.map